### ISSUE TITLE
GWT is broken

### ISSUE THREAD

**Issue by SuperBadger** [TomGrill/gdx-facebook#36] opened 2016-08-10 00:11 UTC
html:compileGwt always fails, everything installed according to wiki instructions:

```
/gdx-facebook-core-1.2.2-sources.jar!/de/tomgrill/gdxfacebook/c
ore/utils/Utils.java'
         [ERROR] Line 46: No source code is available for type java.net.URL; did
 you forget to inherit a required module?
         [ERROR] Line 72: No source code is available for type java.net.Malforme
dURLException; did you forget to inherit a required module?
         [ERROR] Line 81: No source code is available for type java.net.URLDecod
er; did you forget to inherit a required module?
   [ERROR] Aborting compile due to errors in some input files
:html:compileGwt FAILED
```

**Comment by TomGrill** [comment] 2016-08-24 09:55
cannot reproduce. Please create a simple libGDX project which causes this error.

**Comment by aryan9234** [comment] 2016-08-26 15:07
Compiled in super dev mode and debug perfectly, this error occur only when i compile in dist mode for distribution.

**Comment by TomGrill** [comment] 2016-09-01 08:33
fixed with 1.3.0 coming in few hours

**Closed by TomGrill** 2016-09-01 08:33 UTC
